### ISSUE TITLE
Delivery Method for Mailster

### ISSUE THREAD

**Issue by hirenshah** [awesomemotive/wp-mail-logging#112]
I'm using "Easy WP SMTP" for sending emails via my hosting, and "WP Mail Logging" has been capturing everything sent by every other plugin I have.

I just installed "Mailster" and the emails it sends via the delivery methods available, show up in the "WP Mail Logging" logs. Emails sent by other plugins still continue to do so. 

I doubt it's an issue with this plugin, and more to do with "Mailster" bypassing wp_mail() etc but just thought I would ask the question here in case someone knew how to log those emails as well. I think I "Mailster" needs a delivery method that forces it to use wp_mail().

**Comment by hirenshah** [comment]
A hook to use WP Mail Logging for logging would probably be better :)

**Comment by donmhico** [comment]
@hirenshah - Thank you for creating this issue. WP Mail Logging is using the `wp_mail()` hook to log the emails. I'll close this as this is really not an issue, it's just that WP Mail Logging is built to capture emails sent via the official WP function `wp_mail()`.
