### ISSUE TITLE
Mobile screen view issue

### ISSUE THREAD

**Issue by khaninejad** [awesomemotive/wp-mail-logging#123]
Hi,

The Email logs page has an issue with the mobile and small screens. 
![Screenshot_2021-03-31 WP Mail Log ‹ Expert Flooring — WordPress](https://user-images.githubusercontent.com/4404500/113166466-08f54080-9258-11eb-8305-24f1c7deb1dd.png)

**Comment by donmhico** [comment]
@khaninejad - Thank you for creating this ticket. We have solved this issue in the latest version - `1.11.0`. https://a.supportally.com/i/fKf3e4

We will try and improve the display in mobile in the future release.
