### ISSUE TITLE
WP 5.8 Testing 

### ISSUE THREAD

**Issue by EO4wellness** [awesomemotive/wp-mail-logging#127]
Plugin needs to be tested for WordPress 5.8 compatibility. 

Currently the WP plugins repository shows the plug in as 5.5 compatible and displays the message: 
 "Warning: This plugin has not been tested with your current version of WordPress."

**Comment by donmhico** [comment]
Hello @EO4wellness,

Thank you for creating this issue. This has been resolved in the latest version.
