### ISSUE TITLE
Redux framework performs HTTP calls in background and affects performance

### ISSUE THREAD

**Issue by gdarko** [awesomemotive/wp-mail-logging#129]
See screenshot

![Screenshot_2](https://user-images.githubusercontent.com/5760249/133983809-2a750e5a-5d3b-4bb9-b7a5-05d84f401802.png)

**Comment by lkraav** [comment]
Search issues first https://github.com/kgjerstad/wp-mail-logging/issues?q=is%3Aissue+is%3Aopen+redux

**Comment by capuderg** [comment]
Redux Framework was removed in the latest version: 1.11.0.
