### ISSUE TITLE
Gutenberg "Extendify" bloatware library is not disabled when updating in Wordpress

### ISSUE THREAD

**Issue by Socrapop** [awesomemotive/wp-mail-logging#135]
Hey there ! 

I was very confused today when I saw the "Extendify" bloc library added to my gutenberg edit page. I searched for an hour before finding it was coming from this plugin, along the Redux admin panel.
I also found the Extendify blocks are coming from that Redux plugin.

Seeking through your commits, I saw that #47df99cbb310564aaeb13d4b0d3029f034829dc2 was fixing this on activation. 
So I unactivated / reactivated the plugin in Wordpress dashboard and it worked, Extendify disappeared.

You should maybe add the disabling function elsewhere so that it's taken into account when updating with Wordpress dashboard.
You are getting some nasty reviews on the Wordpress Plugin repository because of this :/

Have a nice day,
Camille

**Comment by donmhico** [comment]
@Socrapop - Thank you for creating this ticket. We removed the "Redux" Framework in the latest version - `1.11.0`. I'll close this issue. Feel free to re-open this issue if the issue still persists.
