### ISSUE TITLE
Not logging WooCommerce New Customer Order emails

### ISSUE THREAD

**Issue by gbakeman** [awesomemotive/wp-mail-logging#136]
WP Mail Logging has done a great job so far of logging our emails. After troubleshooting some issues of emails not received, I noticed that the Logger does not log WooCommerce's New Customer Order emails that are sent to our order dispatcher. Is there any particular reason why it would not log these emails?

**Comment by gbakeman** [comment]
[Here's](https://wordpress.org/support/topic/dont-see-all-woocommerce-emails-sent/) a similar discussion on the wp.org plugin page. This person has the **opposite** problem as me: they **can** see new order emails being sent to them, but they **cannot** see the emails going to customers.

**Comment by donmhico** [comment]
@gbakeman - Can you confirm if the issue still persists in the latest version - `1.11.0`? If yes, can you provide steps to reproduce? Unfortunately, we can't reproduce the issue.

**Comment by gbakeman** [comment]
Hi @donmhico ,

It looks like we've been using the logging facility of Post SMTP for some time now. Sorry I couldn't be more help, but thank you for checking in. I'll go ahead and close the issue.
