### ISSUE TITLE
Automatic delete emails doesnt work

### ISSUE THREAD

**Issue by alfredo49** [awesomemotive/wp-mail-logging#138]
Hi:

I have last version of the plugin, i set 29 days to automatic deletion, but it doesnt erase anything, i have emails send in October and they are stored in the list. 

I try to define a max quanty but either works, i defined 25 emails, and now i have 28 in the list

Thxs!

**Comment by capuderg** [comment]
Hi @alfredo49,

thank you for reporting this issue!

Sorry for a late replay, but the automatic deletion is now fixed in the latest version (1.10.5).

Have a nice day and happy holidays!
