### ISSUE TITLE
When was Redux added?

### ISSUE THREAD

**Issue by mitchelldmiller** [awesomemotive/wp-mail-logging#139]
Hello:
I recommended this plugin for use with my Quick Mail plugin, until I tried current version.

Which version of plugin added Redux? Redux is intrusive and unrelated to logging email messages.

I would like to recommend a version of this plugin without Redux.

Thank you, Mitchell

**Comment by lkraav** [comment]
Among other things, Redux now enqueues CSS on frontend.

If only someone had enough bandwidth to PR dropping this bloatware.

**Comment by lkraav** [comment]
Not sure why this issue wasn't linked to the commits, or releases, but https://github.com/awesomemotive/wp-mail-logging/releases/tag/1.11.0 seems to announce Redux has been dropped.

**Comment by capuderg** [comment]
The GH issues were not updated yet, but yes, the Redux framework was removed in 1.11.0, so I'm closing this issue.

**Comment by lkraav** [comment]
> The GH issues were not updated yet, but yes, the Redux framework was removed in 1.11.0, so I'm closing this issue.

Thanks. Ton of duplicates, too, I just noticed.
