### ISSUE TITLE
conflict with emojis in email subjects

### ISSUE THREAD

**Issue by rodrigodlucena** [awesomemotive/wp-mail-logging#144]
One of my clients uses Emojis in certain subjects of woocommerce transactional emails. I found that in these cases there is some kind of bug / conflict because the emails exclusively with Emojis are not "displayed" in the mail log panel. When removing the emojis, the emails are "tracked" again normally, but according to this client, the emojis considerably increase the open rate, so it would be good to correct this conflict in the plugin to accept subjects with emojis

**Comment by donmhico** [comment]
@rodrigodlucena - Thank you for creating this GH issue. We have fixed this issue in #173 and will be included in our next release 🙇
