### ISSUE TITLE
Deprecation notices

### ISSUE THREAD

**Issue by CactusWren2020** [awesomemotive/wp-mail-logging#145]
FYI, you may need to update to be compatible with PHP 8.1:

```PHP Deprecated:  Return type of No3x\WPML\Pimple\Container::offsetGet($id) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/normal_site_dev/wp-content/plugins/wp-mail-logging/lib/vendor/pimple/pimple/src/Container.php on line 93```

**Comment by capuderg** [comment]
Hi  @CactusWren2020,

thank you for reporting this issue. It's fixed in the latest version (1.10.5).

Have a nice day and happy holidays!
