### ISSUE TITLE
UTF8 encoded subjects

### ISSUE THREAD

**Issue by tpaksu** [awesomemotive/wp-mail-logging#146]
Hi, I’ve recently added support for sending base64 encoded subjects in WooCommerce Payments, described on https://ncona.com/2011/06/using-utf-8-characters-on-an-e-mail-subject/ and https://datatracker.ietf.org/doc/html/rfc1342 and it would be perfect if the subjects shown on the mail log would display those with their decoded equivalent.

<img width="2822" alt="image" src="https://user-images.githubusercontent.com/3295/181457917-147c3f05-3c50-457a-935e-d3334aa18e0d.png">

**Comment by donmhico** [comment]
@tpaksu - Thank you for creating this issue. We've resolved this in https://github.com/awesomemotive/wp-mail-logging/pull/162.

**Comment by tpaksu** [comment]
Thanks @donmhico for fixing this issue!
