### ISSUE TITLE
Automatic deletion not working

### ISSUE THREAD

**Issue by leyakoreya** [awesomemotive/wp-mail-logging#148]
Hello!
I noticed that the automatic deletion of old letters does not work after 8 days. What could be the problem?
![Screenshot_3](https://user-images.githubusercontent.com/64163125/187789629-594a8232-1af2-43d5-9371-c52334f67c7c.png)
![Screenshot_1](https://user-images.githubusercontent.com/64163125/187789645-c4dad6cb-38ef-425f-a27e-9946901e4bbb.png)

**Comment by donmhico** [comment]
@leyakoreya - Thank you for creating this issue. Can you try and see if this issue still persists on the latest version - `1.11.0`? Automatic deletion works for me as intended and I can't replicate the issue.

**Comment by donmhico** [comment]
I'll be closing this issue due to the lack of activity. Please feel free to re-open if the issue still persists in the latest version.
