### ISSUE TITLE
Translate "Delete" and "Rename" strings

### ISSUE THREAD

**Issue by nasanansi** [awesomemotive/wp-mail-logging#192]
Translate 2 strings: "Delete" and "Rename" under the Bulk Actions dropdown. 

Screen recording: https://a.supportally.com/v/Yswddq

Thread: https://wordpress.org/support/topic/translating-two-strings/

**Comment by donmhico** [comment]
Thank you for creating this issue. We resolve this issue with https://github.com/awesomemotive/wp-mail-logging/commit/2c6e872760a393a19a762ba1b7a3dad5f3deb646, and we'll include it in the next release.

Let's update the user in the WP.org thread that the issue was resolved after our next release.
