### ISSUE TITLE
[Ultra low priority] Typo/wrong name

### ISSUE THREAD

**Issue by indig0F10w** [awesomemotive/wp-mail-logging#194]
Greetings, listed under "Free mailers: SendLayer, SMTP.com, Sendinblue, Google / Gmail, Mailgun, Postmark, SendGrid."

Sendinblue does not exist anymore, it is called Brevo now.

Thank you for this plugin.

**Comment by donmhico** [comment]
@indig0F10w - Thank you so much for creating this issue. We will include this in our next release.

**Comment by donmhico** [comment]
Again, thank you, @indig0F10w, for reporting this issue. We fixed this with https://github.com/awesomemotive/wp-mail-logging/commit/4aded4e9c38229f5b5bac4e15d4a39691dccc570, and we will include this in our next release.
