### ISSUE TITLE
Add filter to filter logged emails

### ISSUE THREAD

**Issue by floasmf** [awesomemotive/wp-mail-logging#202]
Hello,

Is it possible to add a filter in the **save_email_log** method to define if the email must be logged (example: email to admin, password reset...)?
By default, the filter would be set to true.

Add this to line 531 in src/WPML_Plugin.php
```php
$save = apply_filters( 'wp_mail_logging_save_log_email', true, $mail_data );

if (!$save) {
    return $mail_data;
}
```
In any files of a plugin or theme, you can do the following, for example
```php
add_filter('wp_mail_logging_save_log_email', function($save, $emailData) {
    if ($emailData['to'] == get_option('admin_email')) {
        return false;
    }
    return $save;
}, 10, 2);
```
Best regards,

**Comment by donmhico** [comment]
Thank you for creating this issue! I've responded to a similar inquiry in [wp.org](https://wordpress.org/support/topic/add-filter-saving-log/#post-18213027).
