### ISSUE TITLE
Short circuited wp_mail() calls are still being logged

### ISSUE THREAD

**Issue by tripflex** [awesomemotive/wp-mail-logging#48]
see https://core.trac.wordpress.org/ticket/35069

Right now the only way to short circuit `wp_mail` is to pass an empty `to` and `message` value in the args.  Looks like it's still logging the mail even if the `to` value is empty.

May be something good to add to settings like:

- [ ] Log mails even with empty `to` value

**Comment by donmhico** [comment]
@tripflex - Thanks for creating this ticket. This plugin is intended to capture emails even if it does not have `to` or `message`. But with https://github.com/awesomemotive/wp-mail-logging/pull/167 which will be included in the next update, you should be able to pass `null` in `wp_mail` filter, to prevent WP Mail Logging from logging the email.
