### ISSUE TITLE
Global log for Multisite

### ISSUE THREAD

**Issue by Helmi** [awesomemotive/wp-mail-logging#63]
Hey there,

it would be great to have a global log in network admin for a multisite installation.

**Comment by No3x** [comment]
Can you elaborate on this. What does not work? Each WordPress instance hast it's own logging but you would like to have a global logging?

**Comment by lkraav** [comment]
@No3x could the plugin docs gain a note about current multisite compatibility status?

What can be expected to happen if we network-activate this plugin? Is it guaranteed to work the same as activating on each subsite manually? In this case, network-activation provides a little bit of value already.

**Comment by No3x** [comment]
The status of multisite support is unknown. I'm not familiar with mutlisite and don't run a multisite setup.

**Comment by donmhico** [comment]
Thank you to everyone who contributed to this issue. I'll close this issue due to inactivity and we also don't have any plans in the immediate future to support WP multisite.
