### ISSUE TITLE
Refresh after email resend, sends the emails again

### ISSUE THREAD

**Issue by ghost** [awesomemotive/wp-mail-logging#76]
Steps to reproduce:
1, Go to the past email list,
2, Resend a random email
3, Refresh the page
4, Observe how the email got resent twice.

Why is this a problem
Because I accidentally spammed about 100 users with the same email 5 times

How do you expect us to fix it
Add a redirect to the the list after the resend has been completed, refreshing this will send the GET request, not the POST.

**Comment by No3x** [comment]
This was reported and verified on WordPress.org support forums. I do have a branch working on this, I guess. Have to find and push it next time I'm working on the plugin. But it was not easy to fix it and I was not happy with the status to merge it.
